### ISSUE TITLE
raw counts h5ad objects

### ISSUE THREAD

**Issue by mjstrumillo** [haniffalab/FCA_bone_marrow#7]
Hi, thanks for this great resource! I know you're providing all the fastqs and the h5ad of normalized counts for the non DS FBM, but would it be possible to obtain the non-transformed counts in h5ad with all the metadata? or the h5ad with multiple layers (normalized and raw for the nonDS FBM?) I know I can build it from fastqs but was hoping you might have one ready.
thank you!

**Comment by simonewebb** [comment]
Hi @mjstrumillo!
Of course, that's completely reasonable.

So as to not provide objects that might be deprecated with Scanpy/Seurat updates, we have placed the raw count matrices for each dataset at it's relevant accession (which you can then use to build your preferred object type). The accessions codes are listed in [data availability section in the manuscript](https://www.nature.com/articles/s41586-021-03929-x#data-availability)

So, if you're interested in the non-DS FBM data, you explore ArrayExpress at [accession E-MTAB-9389](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-9389)
and if you click on 'processed data' for non-DS samples, you can [download the csv here](https://www.ebi.ac.uk/biostudies/files/E-MTAB-9389/fbm_tot_gex_20201104.csv )

The raw count matrices are available for all other datasets in same way. I'd recommend using the h5ad with transformed counts [from the portal](https://app.cellatlas.io/fetal-bone-marrow/dataset/5/download), then adding the raw counts in as a layer as needed (since the metadata there is quite comprehensive for most uses). Could also be worth browsing supplementary tables from manuscript, as each dataset has supporting metadata for specific analyses (that you may or may not be interested in).

Hoping that's clear, please shout if not. Any other questions, please just let me know. Thanks!

Simone

**Comment by simonewebb** [comment]
Please feel free to re-open issue if any further questions

**Comment by mjstrumillo** [comment]
oh I see thank you so much! I got confused since its csv not mtx, but looking at the size it makes perfect sense! thank you!

**Comment by simonewebb** [comment]
Ahh I understand. Great news!
